main: ./Lexer.h ./Lexer.cpp ./Tokenizer.h ./Tokenizer.cpp ./Parser.h ./Parser.cpp ./main.cpp
	g++ -std=c++11 -g ./main.cpp ./Lexer.h ./Lexer.cpp ./Tokenizer.h ./Tokenizer.cpp ./Parser.h ./Parser.cpp -o ../AQL
